# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8cfcea2fa53a2a496c546ad454144b804a88604295f3917763796b1d751d3ea7cc9d728880b31c70a88f7e067c0d56fe66458ab7772b2804ff0afe591938ce8

test:
  secret_key_base: bd9b8394c37c3c8ed30b66f4799daf448f783ef55f3a983a2c55735cfb0062585182fa640b2ee65c7b62f2f9a0c2167c1edde1b9bd9343f68679cb87b5f7794e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
